# SPDX-License-Identifier: MIT
# Copyright (C) 2026 chenxin527

name: 构建 U-Boot

on:
  # 暂时只允许手动触发，禁用 push 自动构建。
  workflow_dispatch:

permissions:
  contents: read

jobs:
  core:
    name: 构建代表固件
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v7

      - name: 安装编译依赖
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo ./build.sh install_deps
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: 检查编译依赖
        run: |
          ./build.sh check_deps

      - name: 编译 U-Boot
        run: |
          . ./build.sh build representative

          echo "RELEASE_VERSION=$_RELEASE_VERSION_" >> $GITHUB_ENV

      - name: 上传编译产物
        uses: actions/upload-artifact@v7
        with:
          name: uboot-${{ env.RELEASE_VERSION }}
          path: ./bin/${{ env.RELEASE_VERSION }}/
          if-no-files-found: error
