# SPDX-License-Identifier: MIT
# Copyright (C) 2026 chenxin527

name: 构建并发布

on:
  # 暂时只允许手动触发，禁用 push 自动构建。
  workflow_dispatch:
    inputs:
      PRERELEASE:
        description: '作为预发布版本'
        required: true
        type: boolean
        default: false

env:
  PRERELEASE: ${{ inputs.PRERELEASE }}

permissions: write-all

jobs:
  core:
    name: 构建并发布
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@main

      - name: 安装编译依赖
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo ./build.sh install_deps
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: 检查编译依赖
        run: |
          ./build.sh check_deps

      - name: 编译 U-Boot
        run: |
          . ./build.sh build representative

          echo "RELEASE_VERSION=$_RELEASE_VERSION_" >> $GITHUB_ENV

      - name: 发布 U-Boot
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          files: ./bin/${{ env.RELEASE_VERSION }}/*
          body_path: ./bin/${{ env.RELEASE_VERSION }}/release-${{ env.RELEASE_VERSION }}.md
          prerelease: ${{ env.PRERELEASE == 'true' }}
